baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cloud innovation platform"
[taxonomies]
  category = "categories"

[module]
  [[module.imports]]
    disable= false 
    path = "github.com/cip-core-mirrors/cip-core-portal-theme"